In [7]:
%pip install xgboost


[notice] A new release of pip available: 22.2.2 -> 24.0
[notice] To update, run: python3.10 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [8]:
import pandas as pd

df = pd.read_csv("/Users/rchang/WAT-ai/wildfire/2016_weather.csv")
df.drop(columns=["time", "WindDirection"], inplace=True)
df.to_csv("2016_weather_filtered.csv", index=False)

In [9]:
x = pd.read_csv("2016_weather_filtered.csv")
x = x.values
x

array([[-20.026,   0.6  ,  89.4  , ...,   0.   ,   0.   , -21.3  ],
       [-20.931,   0.6  ,  88.9  , ...,   0.   ,   0.   , -22.3  ],
       [-21.125,   0.6  ,  88.8  , ...,   0.   ,   0.   , -22.5  ],
       ...,
       [ -5.791,   0.6  ,  96.6  , ...,   0.   ,   0.   ,  -6.3  ],
       [ -5.667,   0.6  ,  96.8  , ...,   0.   ,   0.   ,  -6.1  ],
       [ -5.574,   0.6  ,  96.9  , ...,   0.   ,   0.   ,  -6.   ]])

In [10]:
df = pd.read_csv("/Users/rchang/WAT-ai/wildfire/2017_burn.csv")
df.drop(columns=["IGNITION_DATE","LATITUDE","LONGITUDE"], inplace=True)
df.to_csv("2017_burn_filtered.csv", index=False)

In [11]:
y = pd.read_csv("2017_burn_filtered.csv")
y = y.values
y

array([[1.000e-01],
       [0.000e+00],
       [0.000e+00],
       [9.000e-03],
       [9.000e-03],
       [9.000e-03],
       [0.000e+00],
       [9.000e-03],
       [2.000e-02],
       [0.000e+00],
       [2.800e+01],
       [9.000e-03],
       [3.000e-01],
       [9.000e-03],
       [1.000e-01],
       [7.000e-01],
       [2.000e-01],
       [1.500e-02],
       [2.100e+00],
       [9.000e-03],
       [9.000e-03],
       [9.000e-03],
       [0.000e+00],
       [1.500e-02],
       [5.000e-02],
       [2.000e-01],
       [0.000e+00],
       [9.000e-03],
       [0.000e+00],
       [5.770e+02],
       [3.091e+02],
       [2.000e-01],
       [1.400e+01],
       [8.720e+02],
       [0.000e+00],
       [2.000e-01],
       [0.000e+00],
       [1.700e+00],
       [0.000e+00],
       [9.000e-03],
       [0.000e+00],
       [1.790e+03],
       [0.000e+00],
       [3.000e-01],
       [0.000e+00],
       [5.300e+01],
       [4.310e+01],
       [4.000e-01],
       [0.000e+00],
       [2.000e-02],


In [12]:
# check xgboost version
import xgboost
print(xgboost.__version__)

2.0.3


In [13]:
from xgboost import XGBRegressor

model = XGBRegressor(n_estimators=1000, learning_rate=0.01, early_stopping_rounds=50)

In [14]:
# # define model evaluation method
# from numpy import absolute
# from sklearn.model_selection import RepeatedKFold, cross_val_score


# cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
# # evaluate model
# scores = cross_val_score(model, x, y, scoring='neg_mean_absolute_error', cv=cv, n_jobs=-1)

# # force scores to be positive
# scores = absolute(scores)
# print('Mean MAE: %.3f (%.3f)' % (scores.mean(), scores.std()) )

In [15]:
x_new = pd.read_csv("2017_weather_filtered.csv")
x_new = x_new.values
x_new

array([[ -6.642,   0.6  ,  82.2  , ...,   0.   ,   2.77 ,  -9.2  ],
       [ -7.608,   0.6  ,  80.7  , ...,   0.   ,   2.01 , -10.4  ],
       [ -9.066,   0.6  ,  82.9  , ...,   0.   ,   1.51 , -11.4  ],
       ...,
       [ -6.231,   0.6  ,  95.5  , ...,   0.   ,   0.76 ,  -6.8  ],
       [ -7.284,   0.6  ,  94.8  , ...,   0.   ,   1.01 ,  -8.   ],
       [ -8.099,   0.6  ,  94.2  , ...,   0.   ,   1.01 ,  -8.9  ]])

In [31]:
model.fit(x, y, eval_set=[(x, y)], verbose=False)
y_new = model.predict(x_new)
y_new

array([ 2.7887540e+02,  6.5730774e-01,  5.3656739e-01, -9.6832770e-01,
       -9.5595574e-01,  3.0527094e-01,  2.6082912e-01,  2.6082912e-01,
       -1.4414164e-01, -1.4442931e-01,  3.6204083e+00, -1.2057358e+00,
        5.5286098e-01,  5.0044847e-01,  5.0044847e-01, -9.6861535e-01,
       -9.5595574e-01,  1.8133023e-01,  2.7791399e-01,  3.5741267e-01,
       -1.1506568e-01,  5.6350846e-02,  1.1929810e+02,  1.1929810e+02,
        1.1929810e+02,  1.1929810e+02,  4.2423315e+00,  4.2423315e+00,
        1.7958848e+00,  4.2423315e+00,  1.0608743e+01,  8.6641656e+02,
        8.6641656e+02,  8.6641656e+02,  2.2616671e-01,  1.2721886e-02,
        1.4665766e-02,  4.9868178e-02,  1.4665766e-02,  1.4665766e-02,
        1.6145071e-02,  1.4201191e-02,  5.7326233e+02,  1.1605142e-01,
        1.4009618e+01,  8.6641656e+02,  8.6641656e+02,  5.7326233e+02,
        4.0413451e-01,  1.1605142e-01,  1.1605142e-01,  5.7326233e+02,
        3.0934414e-02,  3.0934414e-02,  3.0934414e-02,  3.0934414e-02,
      

In [21]:
import numpy as np
# np.savetxt("y_new.csv", y_new, delimiter=",")
len(y_new)

144

In [33]:
y_comp = np.genfromtxt("2018_burn_filtered.csv", delimiter=',', skip_header=1)
y_comp
# np.savetxt("y_comp.csv", y_comp, delimiter=",")

array([4.0000e+00, 9.0000e-03, 9.0000e-03, 9.0000e-01, 4.0000e+00,
       9.0000e-03, 9.0000e-03, 9.0000e-03, 8.4000e-01, 0.0000e+00,
       1.9000e+00, 9.0000e-01, 9.0000e-01, 1.9000e+00, 0.0000e+00,
       9.0000e-01, 9.0000e-03, 4.0000e+00, 0.0000e+00, 0.0000e+00,
       4.0000e-01, 8.4000e-01, 0.0000e+00, 4.0000e+00, 9.0000e-03,
       1.6500e+02, 5.0000e+00, 1.7600e+01, 1.5000e-01, 5.6000e+00,
       9.0000e-03, 5.6000e+00, 5.0000e+00, 0.0000e+00, 9.0000e-03,
       1.7600e+01, 1.6500e+02, 3.0000e+00, 3.0000e+00, 1.0500e+00,
       1.0500e+00, 9.0000e-03, 0.0000e+00, 9.0000e-03, 9.0000e-03,
       9.0000e-03, 1.0000e-01, 1.4000e+00, 9.0000e-03, 0.0000e+00,
       2.0000e-01, 0.0000e+00, 1.4000e+00, 1.4000e+00, 0.0000e+00,
       3.0000e-01, 1.0000e-01, 0.0000e+00, 9.0000e-03, 2.0000e-01,
       1.4000e+00, 0.0000e+00, 9.0000e-03, 3.0000e-01, 0.0000e+00,
       0.0000e+00, 4.0000e-01, 0.0000e+00, 0.0000e+00, 9.0000e-03,
       5.0000e-01, 9.0000e-03, 0.0000e+00, 4.4000e-01, 5.0000e

In [34]:
diff = y_new - y_comp
diff

array([ 2.74875397e+02,  6.48307744e-01,  5.27567390e-01, -1.86832770e+00,
       -4.95595574e+00,  2.96270940e-01,  2.51829121e-01,  2.51829121e-01,
       -9.84141644e-01, -1.44429311e-01,  1.72040830e+00, -2.10573580e+00,
       -3.47139025e-01, -1.39955153e+00,  5.00448465e-01, -1.86861535e+00,
       -9.64955744e-01, -3.81866977e+00,  2.77913988e-01,  3.57412666e-01,
       -5.15065679e-01, -7.83649154e-01,  1.19298103e+02,  1.15298103e+02,
        1.19289103e+02, -4.57018967e+01, -7.57668495e-01, -1.33576685e+01,
        1.64588485e+00, -1.35766850e+00,  1.05997427e+01,  8.60816565e+02,
        8.61416565e+02,  8.66416565e+02,  2.17166710e-01, -1.75872781e+01,
       -1.64985334e+02, -2.95013182e+00, -2.98533423e+00, -1.03533423e+00,
       -1.03385493e+00,  5.20119125e-03,  5.73262329e+02,  1.07051421e-01,
        1.40006178e+01,  8.66407565e+02,  8.66316565e+02,  5.71862329e+02,
        3.95134512e-01,  1.16051421e-01, -8.39485794e-02,  5.73262329e+02,
       -1.36906559e+00, -

In [ ]:
np.savetxt("delta.csv", diff, delimiter=',')