In [6]:
import pandas as pd
import numpy as np

In [7]:
X = pd.read_csv("./dummy-data/2016_weather_filtered.csv")
X = X.values
X

array([[-20.026,   0.6  ,  89.4  , ...,   0.   ,   0.   , -21.3  ],
       [-20.931,   0.6  ,  88.9  , ...,   0.   ,   0.   , -22.3  ],
       [-21.125,   0.6  ,  88.8  , ...,   0.   ,   0.   , -22.5  ],
       ...,
       [ -5.791,   0.6  ,  96.6  , ...,   0.   ,   0.   ,  -6.3  ],
       [ -5.667,   0.6  ,  96.8  , ...,   0.   ,   0.   ,  -6.1  ],
       [ -5.574,   0.6  ,  96.9  , ...,   0.   ,   0.   ,  -6.   ]])

In [8]:
y = np.genfromtxt("./dummy-data/2017_burn_filtered.csv", delimiter=',', skip_header=1)
y

array([1.000e-01, 0.000e+00, 0.000e+00, 9.000e-03, 9.000e-03, 9.000e-03,
       0.000e+00, 9.000e-03, 2.000e-02, 0.000e+00, 2.800e+01, 9.000e-03,
       3.000e-01, 9.000e-03, 1.000e-01, 7.000e-01, 2.000e-01, 1.500e-02,
       2.100e+00, 9.000e-03, 9.000e-03, 9.000e-03, 0.000e+00, 1.500e-02,
       5.000e-02, 2.000e-01, 0.000e+00, 9.000e-03, 0.000e+00, 5.770e+02,
       3.091e+02, 2.000e-01, 1.400e+01, 8.720e+02, 0.000e+00, 2.000e-01,
       0.000e+00, 1.700e+00, 0.000e+00, 9.000e-03, 0.000e+00, 1.790e+03,
       0.000e+00, 3.000e-01, 0.000e+00, 5.300e+01, 4.310e+01, 4.000e-01,
       0.000e+00, 2.000e-02, 9.000e-03, 0.000e+00, 0.000e+00, 0.000e+00,
       1.180e+01, 0.000e+00, 9.000e-03, 9.000e-03, 0.000e+00, 1.000e-01,
       9.000e-03, 1.800e+00, 9.000e-03, 2.600e-01, 9.000e-01, 9.000e-03,
       9.000e-03, 0.000e+00, 1.000e+00, 9.000e-03, 9.000e-03, 1.500e+00,
       2.000e-02, 0.000e+00, 2.000e-01, 4.000e-02, 1.000e-02, 0.000e+00,
       9.000e-03, 9.000e-03, 9.000e-03, 3.600e+00, 

In [9]:
X_test = pd.read_csv("./dummy-data/2017_weather_filtered.csv")
X_test = X_test.values
X_test

array([[ -6.642,   0.6  ,  82.2  , ...,   0.   ,   2.77 ,  -9.2  ],
       [ -7.608,   0.6  ,  80.7  , ...,   0.   ,   2.01 , -10.4  ],
       [ -9.066,   0.6  ,  82.9  , ...,   0.   ,   1.51 , -11.4  ],
       ...,
       [ -6.231,   0.6  ,  95.5  , ...,   0.   ,   0.76 ,  -6.8  ],
       [ -7.284,   0.6  ,  94.8  , ...,   0.   ,   1.01 ,  -8.   ],
       [ -8.099,   0.6  ,  94.2  , ...,   0.   ,   1.01 ,  -8.9  ]])

In [10]:
y_test = np.genfromtxt("./dummy-data/2018_burn_filtered.csv", delimiter=',', skip_header=1)
y_test

array([4.0000e+00, 9.0000e-03, 9.0000e-03, 9.0000e-01, 4.0000e+00,
       9.0000e-03, 9.0000e-03, 9.0000e-03, 8.4000e-01, 0.0000e+00,
       1.9000e+00, 9.0000e-01, 9.0000e-01, 1.9000e+00, 0.0000e+00,
       9.0000e-01, 9.0000e-03, 4.0000e+00, 0.0000e+00, 0.0000e+00,
       4.0000e-01, 8.4000e-01, 0.0000e+00, 4.0000e+00, 9.0000e-03,
       1.6500e+02, 5.0000e+00, 1.7600e+01, 1.5000e-01, 5.6000e+00,
       9.0000e-03, 5.6000e+00, 5.0000e+00, 0.0000e+00, 9.0000e-03,
       1.7600e+01, 1.6500e+02, 3.0000e+00, 3.0000e+00, 1.0500e+00,
       1.0500e+00, 9.0000e-03, 0.0000e+00, 9.0000e-03, 9.0000e-03,
       9.0000e-03, 1.0000e-01, 1.4000e+00, 9.0000e-03, 0.0000e+00,
       2.0000e-01, 0.0000e+00, 1.4000e+00, 1.4000e+00, 0.0000e+00,
       3.0000e-01, 1.0000e-01, 0.0000e+00, 9.0000e-03, 2.0000e-01,
       1.4000e+00, 0.0000e+00, 9.0000e-03, 3.0000e-01, 0.0000e+00,
       0.0000e+00, 4.0000e-01, 0.0000e+00, 0.0000e+00, 9.0000e-03,
       5.0000e-01, 9.0000e-03, 0.0000e+00, 4.4000e-01, 5.0000e

In [11]:
from xgboost import XGBRegressor

model = XGBRegressor(n_estimators=1000, learning_rate=0.01, early_stopping_rounds=50)

model.fit(X, y, eval_set=[(X_test, y_test)], verbose=False)
predictions = model.predict(X_test)
predictions

array([34.226395, 32.67639 , 32.67639 , 32.533997, 32.533997, 32.533997,
       32.533997, 32.533997, 32.533997, 32.533997, 32.533997, 32.533997,
       32.67639 , 32.67639 , 32.67639 , 32.533997, 32.533997, 32.533997,
       32.533997, 32.533997, 32.533997, 32.533997, 35.57383 , 35.57383 ,
       35.57383 , 35.57383 , 32.628296, 32.628296, 32.533997, 32.628296,
       32.628296, 37.034893, 37.034893, 37.034893, 32.628296, 32.52921 ,
       32.52921 , 32.52921 , 32.52921 , 32.52921 , 32.52921 , 32.52921 ,
       35.57383 , 32.628296, 32.628296, 37.034893, 37.034893, 35.57383 ,
       32.52921 , 32.628296, 32.628296, 35.57383 , 32.52921 , 32.52921 ,
       32.52921 , 32.52921 , 32.52921 , 32.52921 , 32.52921 , 32.52921 ,
       32.52921 , 32.52921 , 32.52921 , 32.52921 , 32.52921 , 32.52921 ,
       32.52921 , 32.52921 , 32.52921 , 32.52921 , 32.52921 , 32.52921 ,
       32.52921 , 32.52921 , 32.52921 , 32.52921 , 32.52921 , 32.52921 ,
       32.52921 , 32.52921 , 32.52921 , 32.52921 , 

In [12]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Calculate MAE
mae = mean_absolute_error(y_test, predictions)
print('Mean Absolute Error:', mae)

# Calculate MSE
mse = mean_squared_error(y_test, predictions)
print('Mean Squared Error:', mse)

# Calculate RMSE
rmse = mean_squared_error(y_test, predictions, squared=False)
print('Root Mean Squared Error:', rmse)

Mean Absolute Error: 218.9589830292596
Mean Squared Error: 3335062.3128846246
Root Mean Squared Error: 1826.2152975168685
