In [4]:
%pip install xgboost

  Using cached xgboost-2.0.3-py3-none-macosx_12_0_arm64.whl (1.9 MB)

[notice] A new release of pip available: 22.2.2 -> 23.3.2
[notice] To update, run: python3.10 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [69]:
import pandas as pd

df = pd.read_csv("/Users/rchang/WAT-ai/wildfire/2016_weather.csv")
df.drop(columns=["time", "WindDirection"], inplace=True)
df.to_csv("2016_weather_filtered.csv", index=False)

In [64]:
x = pd.read_csv("2016_weather_filtered.csv")
x = x.values
x

array([[-20.026,   0.6  ,  89.4  , ...,   0.   ,   0.   , -21.3  ],
       [-20.931,   0.6  ,  88.9  , ...,   0.   ,   0.   , -22.3  ],
       [-21.125,   0.6  ,  88.8  , ...,   0.   ,   0.   , -22.5  ],
       ...,
       [ -5.791,   0.6  ,  96.6  , ...,   0.   ,   0.   ,  -6.3  ],
       [ -5.667,   0.6  ,  96.8  , ...,   0.   ,   0.   ,  -6.1  ],
       [ -5.574,   0.6  ,  96.9  , ...,   0.   ,   0.   ,  -6.   ]])

In [65]:
df = pd.read_csv("/Users/rchang/WAT-ai/wildfire/2017_burn.csv")
df.drop(columns=["IGNITION_DATE","LATITUDE","LONGITUDE"], inplace=True)
df.to_csv("2017_burn_filtered.csv", index=False)

In [66]:
y = pd.read_csv("2017_burn_filtered.csv")
y = y.values
y

array([[1.000e-01],
       [0.000e+00],
       [0.000e+00],
       [9.000e-03],
       [9.000e-03],
       [9.000e-03],
       [0.000e+00],
       [9.000e-03],
       [2.000e-02],
       [0.000e+00],
       [2.800e+01],
       [9.000e-03],
       [3.000e-01],
       [9.000e-03],
       [1.000e-01],
       [7.000e-01],
       [2.000e-01],
       [1.500e-02],
       [2.100e+00],
       [9.000e-03],
       [9.000e-03],
       [9.000e-03],
       [0.000e+00],
       [1.500e-02],
       [5.000e-02],
       [2.000e-01],
       [0.000e+00],
       [9.000e-03],
       [0.000e+00],
       [5.770e+02],
       [3.091e+02],
       [2.000e-01],
       [1.400e+01],
       [8.720e+02],
       [0.000e+00],
       [2.000e-01],
       [0.000e+00],
       [1.700e+00],
       [0.000e+00],
       [9.000e-03],
       [0.000e+00],
       [1.790e+03],
       [0.000e+00],
       [3.000e-01],
       [0.000e+00],
       [5.300e+01],
       [4.310e+01],
       [4.000e-01],
       [0.000e+00],
       [2.000e-02],


In [59]:
# check xgboost version
import xgboost
print(xgboost.__version__)

2.0.3


In [100]:
from xgboost import XGBRegressor

model = XGBRegressor(n_estimators=1000, learning_rate=0.01, early_stopping_rounds=50)

In [67]:
# # define model evaluation method
# from numpy import absolute
# from sklearn.model_selection import RepeatedKFold, cross_val_score


# cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
# # evaluate model
# scores = cross_val_score(model, x, y, scoring='neg_mean_absolute_error', cv=cv, n_jobs=-1)

# # force scores to be positive
# scores = absolute(scores)
# print('Mean MAE: %.3f (%.3f)' % (scores.mean(), scores.std()) )

Mean MAE: 66.496 (64.411)


In [101]:
x_new = pd.read_csv("2017_weather_filtered.csv")
x_new = x_new.values
x_new

array([[ -6.642,   0.6  ,  82.2  , ...,   0.   ,   2.77 ,  -9.2  ],
       [ -7.608,   0.6  ,  80.7  , ...,   0.   ,   2.01 , -10.4  ],
       [ -9.066,   0.6  ,  82.9  , ...,   0.   ,   1.51 , -11.4  ],
       ...,
       [ -6.231,   0.6  ,  95.5  , ...,   0.   ,   0.76 ,  -6.8  ],
       [ -7.284,   0.6  ,  94.8  , ...,   0.   ,   1.01 ,  -8.   ],
       [ -8.099,   0.6  ,  94.2  , ...,   0.   ,   1.01 ,  -8.9  ]])

In [104]:
model.fit(x, y, eval_set=[(x, y)], verbose=False)
y_new = model.predict(x_new)
y_new

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=50,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.01, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=1000, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)

In [86]:
y_comp = pd.read_csv("2018_burn_filtered.csv")
y_comp = y_comp.values
y_comp

array([[4.0000e+00],
       [9.0000e-03],
       [9.0000e-03],
       [9.0000e-01],
       [4.0000e+00],
       [9.0000e-03],
       [9.0000e-03],
       [9.0000e-03],
       [8.4000e-01],
       [0.0000e+00],
       [1.9000e+00],
       [9.0000e-01],
       [9.0000e-01],
       [1.9000e+00],
       [0.0000e+00],
       [9.0000e-01],
       [9.0000e-03],
       [4.0000e+00],
       [0.0000e+00],
       [0.0000e+00],
       [4.0000e-01],
       [8.4000e-01],
       [0.0000e+00],
       [4.0000e+00],
       [9.0000e-03],
       [1.6500e+02],
       [5.0000e+00],
       [1.7600e+01],
       [1.5000e-01],
       [5.6000e+00],
       [9.0000e-03],
       [5.6000e+00],
       [5.0000e+00],
       [0.0000e+00],
       [9.0000e-03],
       [1.7600e+01],
       [1.6500e+02],
       [3.0000e+00],
       [3.0000e+00],
       [1.0500e+00],
       [1.0500e+00],
       [9.0000e-03],
       [0.0000e+00],
       [9.0000e-03],
       [9.0000e-03],
       [9.0000e-03],
       [1.0000e-01],
       [1.400

In [96]:
import numpy as np

diff = np.subtract(y_new, y_comp)
diff

144

In [94]:
np.savetxt("delta.csv", diff, delimiter=',')